"""Central path resolution. Training data lives OUTSIDE the repo
(../ReTop-data/) so the project stays light — see README "Data layout".
Every script inherits these defaults but keeps its --data/--tok override.
"""
import os

ROOT = os.path.dirname(os.path.abspath(__file__))

# /home/yonoob/projects/ReTop-data  (gitignored, outside the repo)
DATA_DIR = os.path.join(os.path.dirname(ROOT), "ReTop-data")

TOKENIZER_PATH = os.path.join(ROOT, "retop_tokenizer.json")

# generated chunked datasets (regenerated by gen_*.py)
CHUNKED = os.path.join(DATA_DIR, "generated", "hmn_data")
RECALL = os.path.join(CHUNKED, "recall")
ARITHMETIC = os.path.join(CHUNKED, "arithmetic")
DISTILL_PYTHON = os.path.join(CHUNKED, "distill_python")
DISTILL_TEMPLATES = os.path.join(CHUNKED, "distill_templates")